// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: feed/proto/msg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_ping           MessageType = 0
	MessageType_quote          MessageType = 1
	MessageType_extended_quote MessageType = 2
	MessageType_daily_quote    MessageType = 3
	MessageType_market_level   MessageType = 4
	MessageType_ohlcv          MessageType = 5
	MessageType_depth          MessageType = 6
	MessageType_all            MessageType = 7
	MessageType_response       MessageType = 8
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "ping",
		1: "quote",
		2: "extended_quote",
		3: "daily_quote",
		4: "market_level",
		5: "ohlcv",
		6: "depth",
		7: "all",
		8: "response",
	}
	MessageType_value = map[string]int32{
		"ping":           0,
		"quote":          1,
		"extended_quote": 2,
		"daily_quote":    3,
		"market_level":   4,
		"ohlcv":          5,
		"depth":          6,
		"all":            7,
		"response":       8,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_proto_msg_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_feed_proto_msg_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{0}
}

type MarketLevel struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Price         *wrapperspb.Int64Value  `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty           *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Nord          *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=nord,proto3" json:"nord,omitempty"`
	Num           *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketLevel) Reset() {
	*x = MarketLevel{}
	mi := &file_feed_proto_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketLevel) ProtoMessage() {}

func (x *MarketLevel) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketLevel.ProtoReflect.Descriptor instead.
func (*MarketLevel) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MarketLevel) GetPrice() *wrapperspb.Int64Value {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *MarketLevel) GetQty() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Qty
	}
	return nil
}

func (x *MarketLevel) GetNord() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Nord
	}
	return nil
}

func (x *MarketLevel) GetNum() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Num
	}
	return nil
}

type Depth struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Tbq           *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=tbq,proto3" json:"tbq,omitempty"`
	Tsq           *wrapperspb.UInt64Value `protobuf:"bytes,2,opt,name=tsq,proto3" json:"tsq,omitempty"`
	Asks          []*MarketLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids          []*MarketLevel          `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Depth) Reset() {
	*x = Depth{}
	mi := &file_feed_proto_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Depth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Depth) ProtoMessage() {}

func (x *Depth) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Depth.ProtoReflect.Descriptor instead.
func (*Depth) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Depth) GetTbq() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Tbq
	}
	return nil
}

func (x *Depth) GetTsq() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Tsq
	}
	return nil
}

func (x *Depth) GetAsks() []*MarketLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *Depth) GetBids() []*MarketLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

type Quote struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Ltp           *wrapperspb.Int64Value  `protobuf:"bytes,1,opt,name=ltp,proto3" json:"ltp,omitempty"`
	Ltt           *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=ltt,proto3" json:"ltt,omitempty"`
	Ltq           *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=ltq,proto3" json:"ltq,omitempty"`
	Vtt           *wrapperspb.UInt64Value `protobuf:"bytes,4,opt,name=vtt,proto3" json:"vtt,omitempty"`
	VttDiff       *wrapperspb.UInt64Value `protobuf:"bytes,5,opt,name=vtt_diff,json=vttDiff,proto3" json:"vtt_diff,omitempty"`
	Oi            *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=oi,proto3" json:"oi,omitempty"`
	Ltpc          *wrapperspb.Int64Value  `protobuf:"bytes,7,opt,name=ltpc,proto3" json:"ltpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_feed_proto_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Quote) GetLtp() *wrapperspb.Int64Value {
	if x != nil {
		return x.Ltp
	}
	return nil
}

func (x *Quote) GetLtt() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Ltt
	}
	return nil
}

func (x *Quote) GetLtq() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Ltq
	}
	return nil
}

func (x *Quote) GetVtt() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Vtt
	}
	return nil
}

func (x *Quote) GetVttDiff() *wrapperspb.UInt64Value {
	if x != nil {
		return x.VttDiff
	}
	return nil
}

func (x *Quote) GetOi() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Oi
	}
	return nil
}

func (x *Quote) GetLtpc() *wrapperspb.Int64Value {
	if x != nil {
		return x.Ltpc
	}
	return nil
}

type ExtendedQuote struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Atp           *wrapperspb.Int64Value  `protobuf:"bytes,1,opt,name=atp,proto3" json:"atp,omitempty"`
	Cp            *wrapperspb.Int64Value  `protobuf:"bytes,2,opt,name=cp,proto3" json:"cp,omitempty"`
	Lc            *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=lc,proto3" json:"lc,omitempty"`
	Uc            *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=uc,proto3" json:"uc,omitempty"`
	Yh            *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=yh,proto3" json:"yh,omitempty"`
	Yl            *wrapperspb.Int64Value  `protobuf:"bytes,6,opt,name=yl,proto3" json:"yl,omitempty"`
	Poi           *wrapperspb.UInt64Value `protobuf:"bytes,7,opt,name=poi,proto3" json:"poi,omitempty"`
	Oich          *wrapperspb.Int64Value  `protobuf:"bytes,8,opt,name=oich,proto3" json:"oich,omitempty"`
	Pc            *wrapperspb.UInt32Value `protobuf:"bytes,9,opt,name=pc,proto3" json:"pc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedQuote) Reset() {
	*x = ExtendedQuote{}
	mi := &file_feed_proto_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedQuote) ProtoMessage() {}

func (x *ExtendedQuote) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedQuote.ProtoReflect.Descriptor instead.
func (*ExtendedQuote) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{3}
}

func (x *ExtendedQuote) GetAtp() *wrapperspb.Int64Value {
	if x != nil {
		return x.Atp
	}
	return nil
}

func (x *ExtendedQuote) GetCp() *wrapperspb.Int64Value {
	if x != nil {
		return x.Cp
	}
	return nil
}

func (x *ExtendedQuote) GetLc() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Lc
	}
	return nil
}

func (x *ExtendedQuote) GetUc() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *ExtendedQuote) GetYh() *wrapperspb.Int64Value {
	if x != nil {
		return x.Yh
	}
	return nil
}

func (x *ExtendedQuote) GetYl() *wrapperspb.Int64Value {
	if x != nil {
		return x.Yl
	}
	return nil
}

func (x *ExtendedQuote) GetPoi() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Poi
	}
	return nil
}

func (x *ExtendedQuote) GetOich() *wrapperspb.Int64Value {
	if x != nil {
		return x.Oich
	}
	return nil
}

func (x *ExtendedQuote) GetPc() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Pc
	}
	return nil
}

type DailyQuote struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Do            *wrapperspb.Int64Value  `protobuf:"bytes,1,opt,name=do,proto3" json:"do,omitempty"`
	Dh            *wrapperspb.Int64Value  `protobuf:"bytes,2,opt,name=dh,proto3" json:"dh,omitempty"`
	Dl            *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=dl,proto3" json:"dl,omitempty"`
	Dc            *wrapperspb.Int64Value  `protobuf:"bytes,4,opt,name=dc,proto3" json:"dc,omitempty"`
	Dhoi          *wrapperspb.UInt64Value `protobuf:"bytes,5,opt,name=dhoi,proto3" json:"dhoi,omitempty"`
	Dloi          *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=dloi,proto3" json:"dloi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyQuote) Reset() {
	*x = DailyQuote{}
	mi := &file_feed_proto_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyQuote) ProtoMessage() {}

func (x *DailyQuote) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyQuote.ProtoReflect.Descriptor instead.
func (*DailyQuote) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{4}
}

func (x *DailyQuote) GetDo() *wrapperspb.Int64Value {
	if x != nil {
		return x.Do
	}
	return nil
}

func (x *DailyQuote) GetDh() *wrapperspb.Int64Value {
	if x != nil {
		return x.Dh
	}
	return nil
}

func (x *DailyQuote) GetDl() *wrapperspb.Int64Value {
	if x != nil {
		return x.Dl
	}
	return nil
}

func (x *DailyQuote) GetDc() *wrapperspb.Int64Value {
	if x != nil {
		return x.Dc
	}
	return nil
}

func (x *DailyQuote) GetDhoi() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Dhoi
	}
	return nil
}

func (x *DailyQuote) GetDloi() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Dloi
	}
	return nil
}

type OHLCV struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Open          *wrapperspb.Int64Value  `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	High          *wrapperspb.Int64Value  `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	Close         *wrapperspb.Int64Value  `protobuf:"bytes,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume        *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Epoch         *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLCV) Reset() {
	*x = OHLCV{}
	mi := &file_feed_proto_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLCV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCV) ProtoMessage() {}

func (x *OHLCV) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCV.ProtoReflect.Descriptor instead.
func (*OHLCV) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{5}
}

func (x *OHLCV) GetOpen() *wrapperspb.Int64Value {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *OHLCV) GetHigh() *wrapperspb.Int64Value {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *OHLCV) GetLow() *wrapperspb.Int64Value {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *OHLCV) GetClose() *wrapperspb.Int64Value {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *OHLCV) GetVolume() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *OHLCV) GetEpoch() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Epoch
	}
	return nil
}

type SymDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticksize      string                 `protobuf:"bytes,1,opt,name=ticksize,proto3" json:"ticksize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymDetail) Reset() {
	*x = SymDetail{}
	mi := &file_feed_proto_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymDetail) ProtoMessage() {}

func (x *SymDetail) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymDetail.ProtoReflect.Descriptor instead.
func (*SymDetail) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{6}
}

func (x *SymDetail) GetTicksize() string {
	if x != nil {
		return x.Ticksize
	}
	return ""
}

type MarketFeed struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Quote         *Quote                  `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	Eq            *ExtendedQuote          `protobuf:"bytes,2,opt,name=eq,proto3" json:"eq,omitempty"`
	Dq            *DailyQuote             `protobuf:"bytes,3,opt,name=dq,proto3" json:"dq,omitempty"`
	Ohlcv         *OHLCV                  `protobuf:"bytes,4,opt,name=ohlcv,proto3" json:"ohlcv,omitempty"`
	Depth         *Depth                  `protobuf:"bytes,5,opt,name=depth,proto3" json:"depth,omitempty"`
	FeedTime      *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=feed_time,json=feedTime,proto3" json:"feed_time,omitempty"`
	SendTime      *wrapperspb.UInt64Value `protobuf:"bytes,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Token         string                  `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	SequenceNo    uint64                  `protobuf:"varint,9,opt,name=sequence_no,json=sequenceNo,proto3" json:"sequence_no,omitempty"`
	Snapshot      bool                    `protobuf:"varint,10,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Ticker        string                  `protobuf:"bytes,11,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Symdetail     *SymDetail              `protobuf:"bytes,12,opt,name=symdetail,proto3" json:"symdetail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketFeed) Reset() {
	*x = MarketFeed{}
	mi := &file_feed_proto_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketFeed) ProtoMessage() {}

func (x *MarketFeed) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketFeed.ProtoReflect.Descriptor instead.
func (*MarketFeed) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{7}
}

func (x *MarketFeed) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *MarketFeed) GetEq() *ExtendedQuote {
	if x != nil {
		return x.Eq
	}
	return nil
}

func (x *MarketFeed) GetDq() *DailyQuote {
	if x != nil {
		return x.Dq
	}
	return nil
}

func (x *MarketFeed) GetOhlcv() *OHLCV {
	if x != nil {
		return x.Ohlcv
	}
	return nil
}

func (x *MarketFeed) GetDepth() *Depth {
	if x != nil {
		return x.Depth
	}
	return nil
}

func (x *MarketFeed) GetFeedTime() *wrapperspb.UInt64Value {
	if x != nil {
		return x.FeedTime
	}
	return nil
}

func (x *MarketFeed) GetSendTime() *wrapperspb.UInt64Value {
	if x != nil {
		return x.SendTime
	}
	return nil
}

func (x *MarketFeed) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MarketFeed) GetSequenceNo() uint64 {
	if x != nil {
		return x.SequenceNo
	}
	return 0
}

func (x *MarketFeed) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *MarketFeed) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *MarketFeed) GetSymdetail() *SymDetail {
	if x != nil {
		return x.Symdetail
	}
	return nil
}

type SocketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Feeds         map[string]*MarketFeed `protobuf:"bytes,2,rep,name=feeds,proto3" json:"feeds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Snapshot      bool                   `protobuf:"varint,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Error         bool                   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocketMessage) Reset() {
	*x = SocketMessage{}
	mi := &file_feed_proto_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketMessage) ProtoMessage() {}

func (x *SocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketMessage.ProtoReflect.Descriptor instead.
func (*SocketMessage) Descriptor() ([]byte, []int) {
	return file_feed_proto_msg_proto_rawDescGZIP(), []int{8}
}

func (x *SocketMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ping
}

func (x *SocketMessage) GetFeeds() map[string]*MarketFeed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *SocketMessage) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *SocketMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SocketMessage) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

var File_feed_proto_msg_proto protoreflect.FileDescriptor

const file_feed_proto_msg_proto_rawDesc = "" +
	"\n" +
	"\x14feed/proto/msg.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd2\x01\n" +
	"\vMarketLevel\x121\n" +
	"\x05price\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05price\x12.\n" +
	"\x03qty\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x03qty\x120\n" +
	"\x04nord\x18\x03 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x04nord\x12.\n" +
	"\x03num\x18\x04 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x03num\"\xab\x01\n" +
	"\x05Depth\x12.\n" +
	"\x03tbq\x18\x01 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x03tbq\x12.\n" +
	"\x03tsq\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x03tsq\x12 \n" +
	"\x04asks\x18\x03 \x03(\v2\f.MarketLevelR\x04asks\x12 \n" +
	"\x04bids\x18\x04 \x03(\v2\f.MarketLevelR\x04bids\"\xde\x02\n" +
	"\x05Quote\x12-\n" +
	"\x03ltp\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x03ltp\x12.\n" +
	"\x03ltt\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x03ltt\x12.\n" +
	"\x03ltq\x18\x03 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x03ltq\x12.\n" +
	"\x03vtt\x18\x04 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x03vtt\x127\n" +
	"\bvtt_diff\x18\x05 \x01(\v2\x1c.google.protobuf.UInt64ValueR\avttDiff\x12,\n" +
	"\x02oi\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x02oi\x12/\n" +
	"\x04ltpc\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\x04ltpc\"\xb0\x03\n" +
	"\rExtendedQuote\x12-\n" +
	"\x03atp\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x03atp\x12+\n" +
	"\x02cp\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02cp\x12,\n" +
	"\x02lc\x18\x03 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x02lc\x12,\n" +
	"\x02uc\x18\x04 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x02uc\x12+\n" +
	"\x02yh\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02yh\x12+\n" +
	"\x02yl\x18\x06 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02yl\x12.\n" +
	"\x03poi\x18\a \x01(\v2\x1c.google.protobuf.UInt64ValueR\x03poi\x12/\n" +
	"\x04oich\x18\b \x01(\v2\x1b.google.protobuf.Int64ValueR\x04oich\x12,\n" +
	"\x02pc\x18\t \x01(\v2\x1c.google.protobuf.UInt32ValueR\x02pc\"\xa4\x02\n" +
	"\n" +
	"DailyQuote\x12+\n" +
	"\x02do\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02do\x12+\n" +
	"\x02dh\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02dh\x12+\n" +
	"\x02dl\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02dl\x12+\n" +
	"\x02dc\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x02dc\x120\n" +
	"\x04dhoi\x18\x05 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x04dhoi\x120\n" +
	"\x04dloi\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x04dloi\"\xb5\x02\n" +
	"\x05OHLCV\x12/\n" +
	"\x04open\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x04open\x12/\n" +
	"\x04high\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x04high\x12-\n" +
	"\x03low\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x03low\x121\n" +
	"\x05close\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05close\x124\n" +
	"\x06volume\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06volume\x122\n" +
	"\x05epoch\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x05epoch\"'\n" +
	"\tSymDetail\x12\x1a\n" +
	"\bticksize\x18\x01 \x01(\tR\bticksize\"\xae\x03\n" +
	"\n" +
	"MarketFeed\x12\x1c\n" +
	"\x05quote\x18\x01 \x01(\v2\x06.QuoteR\x05quote\x12\x1e\n" +
	"\x02eq\x18\x02 \x01(\v2\x0e.ExtendedQuoteR\x02eq\x12\x1b\n" +
	"\x02dq\x18\x03 \x01(\v2\v.DailyQuoteR\x02dq\x12\x1c\n" +
	"\x05ohlcv\x18\x04 \x01(\v2\x06.OHLCVR\x05ohlcv\x12\x1c\n" +
	"\x05depth\x18\x05 \x01(\v2\x06.DepthR\x05depth\x129\n" +
	"\tfeed_time\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueR\bfeedTime\x129\n" +
	"\tsend_time\x18\a \x01(\v2\x1c.google.protobuf.UInt64ValueR\bsendTime\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x1f\n" +
	"\vsequence_no\x18\t \x01(\x04R\n" +
	"sequenceNo\x12\x1a\n" +
	"\bsnapshot\x18\n" +
	" \x01(\bR\bsnapshot\x12\x16\n" +
	"\x06ticker\x18\v \x01(\tR\x06ticker\x12(\n" +
	"\tsymdetail\x18\f \x01(\v2\n" +
	".SymDetailR\tsymdetail\"\xed\x01\n" +
	"\rSocketMessage\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.MessageTypeR\x04type\x12/\n" +
	"\x05feeds\x18\x02 \x03(\v2\x19.SocketMessage.FeedsEntryR\x05feeds\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\bR\bsnapshot\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x14\n" +
	"\x05error\x18\x05 \x01(\bR\x05error\x1aE\n" +
	"\n" +
	"FeedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.MarketFeedR\x05value:\x028\x01*\x86\x01\n" +
	"\vMessageType\x12\b\n" +
	"\x04ping\x10\x00\x12\t\n" +
	"\x05quote\x10\x01\x12\x12\n" +
	"\x0eextended_quote\x10\x02\x12\x0f\n" +
	"\vdaily_quote\x10\x03\x12\x10\n" +
	"\fmarket_level\x10\x04\x12\t\n" +
	"\x05ohlcv\x10\x05\x12\t\n" +
	"\x05depth\x10\x06\x12\a\n" +
	"\x03all\x10\a\x12\f\n" +
	"\bresponse\x10\bB1Z/github.com/karanshergill/algotrix-go/feed/protob\x06proto3"

var (
	file_feed_proto_msg_proto_rawDescOnce sync.Once
	file_feed_proto_msg_proto_rawDescData []byte
)

func file_feed_proto_msg_proto_rawDescGZIP() []byte {
	file_feed_proto_msg_proto_rawDescOnce.Do(func() {
		file_feed_proto_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_proto_msg_proto_rawDesc), len(file_feed_proto_msg_proto_rawDesc)))
	})
	return file_feed_proto_msg_proto_rawDescData
}

var file_feed_proto_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feed_proto_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_feed_proto_msg_proto_goTypes = []any{
	(MessageType)(0),               // 0: MessageType
	(*MarketLevel)(nil),            // 1: MarketLevel
	(*Depth)(nil),                  // 2: Depth
	(*Quote)(nil),                  // 3: Quote
	(*ExtendedQuote)(nil),          // 4: ExtendedQuote
	(*DailyQuote)(nil),             // 5: DailyQuote
	(*OHLCV)(nil),                  // 6: OHLCV
	(*SymDetail)(nil),              // 7: SymDetail
	(*MarketFeed)(nil),             // 8: MarketFeed
	(*SocketMessage)(nil),          // 9: SocketMessage
	nil,                            // 10: SocketMessage.FeedsEntry
	(*wrapperspb.Int64Value)(nil),  // 11: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 12: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 13: google.protobuf.UInt64Value
}
var file_feed_proto_msg_proto_depIdxs = []int32{
	11, // 0: MarketLevel.price:type_name -> google.protobuf.Int64Value
	12, // 1: MarketLevel.qty:type_name -> google.protobuf.UInt32Value
	12, // 2: MarketLevel.nord:type_name -> google.protobuf.UInt32Value
	12, // 3: MarketLevel.num:type_name -> google.protobuf.UInt32Value
	13, // 4: Depth.tbq:type_name -> google.protobuf.UInt64Value
	13, // 5: Depth.tsq:type_name -> google.protobuf.UInt64Value
	1,  // 6: Depth.asks:type_name -> MarketLevel
	1,  // 7: Depth.bids:type_name -> MarketLevel
	11, // 8: Quote.ltp:type_name -> google.protobuf.Int64Value
	12, // 9: Quote.ltt:type_name -> google.protobuf.UInt32Value
	12, // 10: Quote.ltq:type_name -> google.protobuf.UInt32Value
	13, // 11: Quote.vtt:type_name -> google.protobuf.UInt64Value
	13, // 12: Quote.vtt_diff:type_name -> google.protobuf.UInt64Value
	13, // 13: Quote.oi:type_name -> google.protobuf.UInt64Value
	11, // 14: Quote.ltpc:type_name -> google.protobuf.Int64Value
	11, // 15: ExtendedQuote.atp:type_name -> google.protobuf.Int64Value
	11, // 16: ExtendedQuote.cp:type_name -> google.protobuf.Int64Value
	12, // 17: ExtendedQuote.lc:type_name -> google.protobuf.UInt32Value
	12, // 18: ExtendedQuote.uc:type_name -> google.protobuf.UInt32Value
	11, // 19: ExtendedQuote.yh:type_name -> google.protobuf.Int64Value
	11, // 20: ExtendedQuote.yl:type_name -> google.protobuf.Int64Value
	13, // 21: ExtendedQuote.poi:type_name -> google.protobuf.UInt64Value
	11, // 22: ExtendedQuote.oich:type_name -> google.protobuf.Int64Value
	12, // 23: ExtendedQuote.pc:type_name -> google.protobuf.UInt32Value
	11, // 24: DailyQuote.do:type_name -> google.protobuf.Int64Value
	11, // 25: DailyQuote.dh:type_name -> google.protobuf.Int64Value
	11, // 26: DailyQuote.dl:type_name -> google.protobuf.Int64Value
	11, // 27: DailyQuote.dc:type_name -> google.protobuf.Int64Value
	13, // 28: DailyQuote.dhoi:type_name -> google.protobuf.UInt64Value
	13, // 29: DailyQuote.dloi:type_name -> google.protobuf.UInt64Value
	11, // 30: OHLCV.open:type_name -> google.protobuf.Int64Value
	11, // 31: OHLCV.high:type_name -> google.protobuf.Int64Value
	11, // 32: OHLCV.low:type_name -> google.protobuf.Int64Value
	11, // 33: OHLCV.close:type_name -> google.protobuf.Int64Value
	12, // 34: OHLCV.volume:type_name -> google.protobuf.UInt32Value
	12, // 35: OHLCV.epoch:type_name -> google.protobuf.UInt32Value
	3,  // 36: MarketFeed.quote:type_name -> Quote
	4,  // 37: MarketFeed.eq:type_name -> ExtendedQuote
	5,  // 38: MarketFeed.dq:type_name -> DailyQuote
	6,  // 39: MarketFeed.ohlcv:type_name -> OHLCV
	2,  // 40: MarketFeed.depth:type_name -> Depth
	13, // 41: MarketFeed.feed_time:type_name -> google.protobuf.UInt64Value
	13, // 42: MarketFeed.send_time:type_name -> google.protobuf.UInt64Value
	7,  // 43: MarketFeed.symdetail:type_name -> SymDetail
	0,  // 44: SocketMessage.type:type_name -> MessageType
	10, // 45: SocketMessage.feeds:type_name -> SocketMessage.FeedsEntry
	8,  // 46: SocketMessage.FeedsEntry.value:type_name -> MarketFeed
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_feed_proto_msg_proto_init() }
func file_feed_proto_msg_proto_init() {
	if File_feed_proto_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_msg_proto_rawDesc), len(file_feed_proto_msg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feed_proto_msg_proto_goTypes,
		DependencyIndexes: file_feed_proto_msg_proto_depIdxs,
		EnumInfos:         file_feed_proto_msg_proto_enumTypes,
		MessageInfos:      file_feed_proto_msg_proto_msgTypes,
	}.Build()
	File_feed_proto_msg_proto = out.File
	file_feed_proto_msg_proto_goTypes = nil
	file_feed_proto_msg_proto_depIdxs = nil
}
